# This file has been generated by mcfn - the mcfunction preprocessor.
# https://github.com/allay-mc/mcfn/

scoreboard objectived add x dummy
scoreboard players set @s x 42
scoreboard objectives remove x