# This file has been generated by mcfn - the mcfunction preprocessor.
# https://github.com/allay-mc/mcfn/

scoreboard objectives add __mcfn_internal_0 dummy
scoreboard players set __mcfn_internal __mcfn_internal_0 0
execute if scores __mcfn_internal __mcfn_internal_0 matches 1 run say Hello
execute unless scores __mcfn_internal __mcfn_internal_0 matches 1 run say Bye
