# This file has been generated by mcfn - the mcfunction preprocessor.
# https://github.com/allay-mc/mcfn/

execute if score core num matches 3 run say Fizz
execute if score core num matches 3 run execute if score core num matches 5 run say Buzz
execute if score core num matches 3 run execute if score core num matches 5 run say FizzBuzz
